function rst_view(rst, rv, sv, dim, RSLIM, PKTRACE, h_sub)
% RST_VIEW view the rate-scale plot along the time or frequency axis
%	rst_view(rst, rv, sv, dim, RSLIM, PKTRACE, h_sub);
%	rst	: scale-rate-time (or freq.) matrix 
%	rv	: rate vector in Hz, e.g., 2.^(1:.5:5).
%	sv	: sacel vector in cyc/oct, e.g., 2.^(-2:.5:3).
%	dim	: dimension to be collaspped 
%			default = 0:none; 1:scale; 2:rate; 3:time(freq.)
%	RSLIM	: max. value of colormap
%	PKTRACE : (optional) peak-trace plot (default = 0)
%		  0: rate-scale response plot
%		  1: rate-scale peak-trace plot
%		  2: enhanced rate-scale plot using Laplacian weighting
%	h_sub	: (optional) handles of subplots
%				(1 plot for dim = 2, otherwise, 2 subplots)
%
%	RST_VIEW views the output has to be generated by COR2RST, AUD2RST.
%	This function will plot the negative rate plot in the left panel,
%	and positive one on the right panel. If PKTRACE > 0, a peak-trace
%	plot will be displayed. The handle of subplots can preassigned 
%	through [h_sub].
%	See also: COR2RST, AUD2COR, AUD2RST

% Auther: Powen Ru (powen@isr.umd.edu), NSL, UMD
% v1.00: 01-Jun-97
% v1.01: 14-Jun-97, colormap changed from <jet> to <a1map>
% v1.02: 25-Jun-97, included peak trace option, colormap auto-detect,
%		    fixed RSLIM, subplot assignment 
% v1.03: 26-Jun-97, included Laplacian weighting
% v1.04: 30-Jul-97, make it executable in Matlab4

% Revision: Taishih Chi (tschi@isr.umd.edu), NSL, UMD
% v1.10: 14-Dec-98, make rst 3 dimensional representation
% v1.20: 18-Dec-98, add 'dim' parameter to display 2D or 3D plot, add 'RSLIM'

global TICKLABEL VER;

% options
if nargin < 4, dim = 0; end;
if (nargin < 6 | dim ~= 0), PKTRACE = 0; else, rs1 = 0; rs2 = 0; end;
if nargin < 7,
   if (dim == 2), h_sub = [subplot(1,1,1)];
   else h_sub = [subplot(121) subplot(122)]; end;
end;
% collaspped rst and check dimension

if (dim == 3)			% 2D plot (collasp time or freq. axis)
   rst = mean(rst, 3);
elseif (dim == 1)		% 2D plot (collasp scale axis)
   rst = squeeze(mean(rst, 1))';
elseif (dim == 2)		% 2D plot (collasp rate scale)
	rst = squeeze(mean(rst, 2));   
end

if (dim == 2), K1 = size(rst, 2); else K1 = length(rv); end;
K2 = size(rst, 1);
if (dim == 0), N = size(rst, 3); else N = 1; end;

if (dim ~= 1)
	if length(sv) ~= K2, error('Scale size mismatch !'); end;
end
if (dim ~= 2)
	if K1 ~= size(rst, 2)/2, error('Rate size mismatch !'); end;
end

sgnstr	= '-+';

% graphics parameter
NTIMES	= 2;	dK = 2^(-NTIMES);
max_rs	= max(rst(:));
if nargin < 5, RSLIM	= max_rs/1.2; end

disp(sprintf('Max: %3.1e; Mean: %3.1e', max_rs, mean(rst(:))));

% xtick labels
if (dim ~= 2)				% dim ~= 2 --> x axis = rate axis
xtic = []; xtlabel = []; Kx = 5;
for k = 1:K1,
	R1 = log2(rv(k));
	if abs(R1-round(R1)) < .001,
		xtic = [xtic k];
		xtlabel = [xtlabel; '-', sprintf('%5.1f', rv(k))];
	end;
end;
end
% ytick labels
if (dim ~= 1)				% dim ~= 1 --> y axis = scale axis
ytic = []; ytlabel = [];
for k = 1:K2,
        R1 = log2(sv(k));
        if abs(R1-round(R1)) < .001,
                ytic = [ytic k];
                ytlabel = [ytlabel; sprintf('%4.2f', sv(k))];
        end;
end;
end

% detect colormap
A1MAP = isa1map;

if (dim ~= 2)				% contain rate axis (2 subplots)
for n = 1:N,
	for sgdx = 1:2,
		% select subplot 
		subplot(h_sub(sgdx));

		% constructing rate-scale matrix
		
		rs0 = rst(:, (1:K1)+(sgdx-1)*K1, n);
		% select ploting object
		if PKTRACE,
			if VER < 5,
				rs0 = interp2(1:K1, 1:K2, rs0, ...
                                        1:.5:K1, 1:.5:K2, 'cubic');
			else,
				rs0 = interp2(rs0, 1, 'cubic');
			end;
			if PKTRACE == 2,
				rsw = del2(rs0);
				rsw = rsw / max(rsw(:)); 
			else,
				rsw = peakpick(rs0, 2);
			end;
			%rs0 = rsw .* rs0;
			rs0 = rsw * max(rs0(:))/2;

			if sgdx == 1,
				rs0 = rs0*.6 + rs1*.4; rs1 = rs0;
			else
				rs0 = rs0*.6 + rs2*.4; rs2 = rs0;
			end;
		else,					% PKTRACE
		if (dim == 1)				% 2D (time, rate)
			rs0 = interp2(rs0, 1:dK:K1, [1:K2]', 'cubic');
		else					% 2D (scale, rate)
			if VER < 5,
				rs0 = interp2(1:K1, 1:K2, rs0, ...
					1:dK:K1, 1:dK:K2, 'cubic');
			else,
				rs0 = interp2(rs0, NTIMES, 'cubic');
			end;
		end					% (dim == 1)
	end;						% PKTRACE

		% select colormap 
		if A1MAP,
			rs0 = real_col(rs0, RSLIM);
			image(1:K1, 1:K2, rs0);
		else,
			imagesc(1:K1, 1:K2, rs0, [0 RSLIM]);
		end;
		axis xy;

		if sgdx == 1, set(gca, 'Xdir', 'rev'); end;
		if (N~=1)
		text('position', [(K1+1)/2 K2*.9], 'str', ...
			[num2str(n) sgnstr(sgdx)], ...
			'fontsi', 16, 'co', 'k', 'ho', 'ce');
		end
		if (dim == 1)				% 2D (time, rate)
			set(gca, 'xtick', xtic, ...
				['x' TICKLABEL], xtlabel(:, sgdx:Kx), ...
				'fontsi', 10);
		else					% 2D (scale rate)
			set(gca, 'xtick', xtic, ...
				['x' TICKLABEL], xtlabel(:, sgdx:Kx), ...
				'ytick', ytic, ['y' TICKLABEL], ytlabel, ...
				'fontsi', 10);
		end
	end;		% end sgdx
	drawnow;
end;
else						% without rate axis (1 subplot)
	subplot(h_sub);
	rs0 = interp2(rst, 1:K1, [1:dK:K2]', 'cubic');
	if A1MAP,
		rs0 = real_col(rs0, RSLIM);
		image(1:K1, 1:K2, rs0);
	else,
		imagesc(1:K1, 1:K2, rs0, [0 RSLIM]);
	end;
	axis xy;
	set(gca, 'ytick', ytic, ['y' TICKLABEL], ytlabel,'fontsi', 10);
	
end
